{-
   SendinBlue API

   SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 

   OpenAPI Version: 3.0.1
   SendinBlue API API version: 3.0.0
   Contact: contact@sendinblue.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SendinBlue.API.EmailCampaigns
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module SendinBlue.API.EmailCampaigns where

import SendinBlue.Core
import SendinBlue.MimeTypes
import SendinBlue.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** EmailCampaigns

-- *** createEmailCampaign0

-- | @POST \/emailCampaigns@
-- 
-- Create an email campaign
-- 
-- AuthMethod: 'AuthApiKeyApiKey'
-- 
createEmailCampaign0
  :: (Consumes CreateEmailCampaign0 MimeJSON, MimeRender MimeJSON CreateEmailCampaign)
  => CreateEmailCampaign -- ^ "emailCampaigns" -  Values to create a campaign
  -> SendinBlueRequest CreateEmailCampaign0 MimeJSON CreateModel MimeJSON
createEmailCampaign0 emailCampaigns =
  _mkRequest "POST" ["/emailCampaigns"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyApiKey)
    `setBodyParam` emailCampaigns

data CreateEmailCampaign0 

-- | /Body Param/ "emailCampaigns" - Values to create a campaign
instance HasBodyParam CreateEmailCampaign0 CreateEmailCampaign 

-- | @application/json@
instance Consumes CreateEmailCampaign0 MimeJSON

-- | @application/json@
instance Produces CreateEmailCampaign0 MimeJSON


-- *** deleteEmailCampaign

-- | @DELETE \/emailCampaigns\/{campaignId}@
-- 
-- Delete an email campaign
-- 
-- AuthMethod: 'AuthApiKeyApiKey'
-- 
deleteEmailCampaign
  :: CampaignId -- ^ "campaignId" -  id of the campaign
  -> SendinBlueRequest DeleteEmailCampaign MimeNoContent NoContent MimeNoContent
deleteEmailCampaign (CampaignId campaignId) =
  _mkRequest "DELETE" ["/emailCampaigns/",toPath campaignId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyApiKey)

data DeleteEmailCampaign  
instance Produces DeleteEmailCampaign MimeNoContent


-- *** emailExportRecipients0

-- | @POST \/emailCampaigns\/{campaignId}\/exportRecipients@
-- 
-- Export the recipients of an email campaign
-- 
-- AuthMethod: 'AuthApiKeyApiKey'
-- 
emailExportRecipients0
  :: (Consumes EmailExportRecipients0 MimeJSON)
  => CampaignId -- ^ "campaignId" -  Id of the campaign
  -> SendinBlueRequest EmailExportRecipients0 MimeJSON CreatedProcessId MimeJSON
emailExportRecipients0 (CampaignId campaignId) =
  _mkRequest "POST" ["/emailCampaigns/",toPath campaignId,"/exportRecipients"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyApiKey)

data EmailExportRecipients0 

-- | /Body Param/ "recipientExport" - Values to send for a recipient export request
instance HasBodyParam EmailExportRecipients0 EmailExportRecipients 

-- | @application/json@
instance Consumes EmailExportRecipients0 MimeJSON

-- | @application/json@
instance Produces EmailExportRecipients0 MimeJSON


-- *** getAbTestCampaignResult

-- | @GET \/emailCampaigns\/{campaignId}\/abTestCampaignResult@
-- 
-- Get an A/B test email campaign results
-- 
-- Obtain winning version of an A/B test email campaign
-- 
-- AuthMethod: 'AuthApiKeyApiKey'
-- 
getAbTestCampaignResult
  :: CampaignId -- ^ "campaignId" -  Id of the A/B test campaign
  -> SendinBlueRequest GetAbTestCampaignResult MimeNoContent AbTestCampaignResult MimeJSON
getAbTestCampaignResult (CampaignId campaignId) =
  _mkRequest "GET" ["/emailCampaigns/",toPath campaignId,"/abTestCampaignResult"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyApiKey)

data GetAbTestCampaignResult  
-- | @application/json@
instance Produces GetAbTestCampaignResult MimeJSON


-- *** getEmailCampaign0

-- | @GET \/emailCampaigns\/{campaignId}@
-- 
-- Get an email campaign report
-- 
-- AuthMethod: 'AuthApiKeyApiKey'
-- 
getEmailCampaign0
  :: CampaignId -- ^ "campaignId" -  Id of the campaign
  -> SendinBlueRequest GetEmailCampaign0 MimeNoContent GetEmailCampaign MimeJSON
getEmailCampaign0 (CampaignId campaignId) =
  _mkRequest "GET" ["/emailCampaigns/",toPath campaignId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyApiKey)

data GetEmailCampaign0  
-- | @application/json@
instance Produces GetEmailCampaign0 MimeJSON


-- *** getEmailCampaigns0

-- | @GET \/emailCampaigns@
-- 
-- Return all your created email campaigns
-- 
-- AuthMethod: 'AuthApiKeyApiKey'
-- 
getEmailCampaigns0
  :: Accept accept -- ^ request accept ('MimeType')
  -> SendinBlueRequest GetEmailCampaigns0 MimeNoContent GetEmailCampaigns accept
getEmailCampaigns0  _ =
  _mkRequest "GET" ["/emailCampaigns"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyApiKey)

data GetEmailCampaigns0  

-- | /Optional Param/ "type" - Filter on the type of the campaigns
instance HasOptionalParam GetEmailCampaigns0 ParamType where
  applyOptionalParam req (ParamType xs) =
    req `addQuery` toQuery ("type", Just xs)

-- | /Optional Param/ "status" - Filter on the status of the campaign
instance HasOptionalParam GetEmailCampaigns0 Status where
  applyOptionalParam req (Status xs) =
    req `addQuery` toQuery ("status", Just xs)

-- | /Optional Param/ "startDate" - Mandatory if endDate is used. Starting (urlencoded) UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ) to filter the sent email campaigns. Prefer to pass your timezone in date-time format for accurate result ( only available if either 'status' not passed and if passed is set to 'sent' )
instance HasOptionalParam GetEmailCampaigns0 StartDate where
  applyOptionalParam req (StartDate xs) =
    req `addQuery` toQuery ("startDate", Just xs)

-- | /Optional Param/ "endDate" - Mandatory if startDate is used. Ending (urlencoded) UTC date-time (YYYY-MM-DDTHH:mm:ss.SSSZ) to filter the sent email campaigns. Prefer to pass your timezone in date-time format for accurate result ( only available if either 'status' not passed and if passed is set to 'sent' )
instance HasOptionalParam GetEmailCampaigns0 EndDate where
  applyOptionalParam req (EndDate xs) =
    req `addQuery` toQuery ("endDate", Just xs)

-- | /Optional Param/ "limit" - Number of documents per page
instance HasOptionalParam GetEmailCampaigns0 Limit where
  applyOptionalParam req (Limit xs) =
    req `addQuery` toQuery ("limit", Just xs)

-- | /Optional Param/ "offset" - Index of the first document in the page
instance HasOptionalParam GetEmailCampaigns0 Offset where
  applyOptionalParam req (Offset xs) =
    req `addQuery` toQuery ("offset", Just xs)
-- | @applications/json@
instance Produces GetEmailCampaigns0 MimeApplicationsJson
-- | @application/json@
instance Produces GetEmailCampaigns0 MimeJSON


-- *** getSharedTemplateUrl0

-- | @GET \/emailCampaigns\/{campaignId}\/sharedUrl@
-- 
-- Get a shared template url
-- 
-- Get a unique URL to share & import an email template from one Sendinblue account to another.
-- 
-- AuthMethod: 'AuthApiKeyApiKey'
-- 
getSharedTemplateUrl0
  :: CampaignId -- ^ "campaignId" -  Id of the campaign or template
  -> SendinBlueRequest GetSharedTemplateUrl0 MimeNoContent GetSharedTemplateUrl MimeJSON
getSharedTemplateUrl0 (CampaignId campaignId) =
  _mkRequest "GET" ["/emailCampaigns/",toPath campaignId,"/sharedUrl"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyApiKey)

data GetSharedTemplateUrl0  
-- | @application/json@
instance Produces GetSharedTemplateUrl0 MimeJSON


-- *** sendEmailCampaignNow

-- | @POST \/emailCampaigns\/{campaignId}\/sendNow@
-- 
-- Send an email campaign immediately, based on campaignId
-- 
-- AuthMethod: 'AuthApiKeyApiKey'
-- 
sendEmailCampaignNow
  :: CampaignId -- ^ "campaignId" -  Id of the campaign
  -> SendinBlueRequest SendEmailCampaignNow MimeNoContent NoContent MimeNoContent
sendEmailCampaignNow (CampaignId campaignId) =
  _mkRequest "POST" ["/emailCampaigns/",toPath campaignId,"/sendNow"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyApiKey)

data SendEmailCampaignNow  
instance Produces SendEmailCampaignNow MimeNoContent


-- *** sendReport0

-- | @POST \/emailCampaigns\/{campaignId}\/sendReport@
-- 
-- Send the report of a campaign
-- 
-- A PDF will be sent to the specified email addresses
-- 
-- AuthMethod: 'AuthApiKeyApiKey'
-- 
sendReport0
  :: (Consumes SendReport0 MimeJSON, MimeRender MimeJSON SendReport)
  => SendReport -- ^ "sendReport" -  Values for send a report
  -> CampaignId -- ^ "campaignId" -  Id of the campaign
  -> SendinBlueRequest SendReport0 MimeJSON NoContent MimeNoContent
sendReport0 sendReport (CampaignId campaignId) =
  _mkRequest "POST" ["/emailCampaigns/",toPath campaignId,"/sendReport"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyApiKey)
    `setBodyParam` sendReport

data SendReport0 

-- | /Body Param/ "sendReport" - Values for send a report
instance HasBodyParam SendReport0 SendReport 

-- | @application/json@
instance Consumes SendReport0 MimeJSON

instance Produces SendReport0 MimeNoContent


-- *** sendTestEmail0

-- | @POST \/emailCampaigns\/{campaignId}\/sendTest@
-- 
-- Send an email campaign to your test list
-- 
-- AuthMethod: 'AuthApiKeyApiKey'
-- 
sendTestEmail0
  :: (Consumes SendTestEmail0 MimeJSON, MimeRender MimeJSON SendTestEmail)
  => SendTestEmail -- ^ "emailTo"
  -> CampaignId -- ^ "campaignId" -  Id of the campaign
  -> SendinBlueRequest SendTestEmail0 MimeJSON NoContent MimeNoContent
sendTestEmail0 emailTo (CampaignId campaignId) =
  _mkRequest "POST" ["/emailCampaigns/",toPath campaignId,"/sendTest"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyApiKey)
    `setBodyParam` emailTo

data SendTestEmail0 
instance HasBodyParam SendTestEmail0 SendTestEmail 

-- | @application/json@
instance Consumes SendTestEmail0 MimeJSON

instance Produces SendTestEmail0 MimeNoContent


-- *** updateCampaignStatus0

-- | @PUT \/emailCampaigns\/{campaignId}\/status@
-- 
-- Update an email campaign status
-- 
-- AuthMethod: 'AuthApiKeyApiKey'
-- 
updateCampaignStatus0
  :: (Consumes UpdateCampaignStatus0 MimeJSON, MimeRender MimeJSON UpdateCampaignStatus)
  => UpdateCampaignStatus -- ^ "status" -  Status of the campaign
  -> CampaignId -- ^ "campaignId" -  Id of the campaign
  -> SendinBlueRequest UpdateCampaignStatus0 MimeJSON NoContent MimeNoContent
updateCampaignStatus0 status (CampaignId campaignId) =
  _mkRequest "PUT" ["/emailCampaigns/",toPath campaignId,"/status"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyApiKey)
    `setBodyParam` status

data UpdateCampaignStatus0 

-- | /Body Param/ "status" - Status of the campaign
instance HasBodyParam UpdateCampaignStatus0 UpdateCampaignStatus 

-- | @application/json@
instance Consumes UpdateCampaignStatus0 MimeJSON

instance Produces UpdateCampaignStatus0 MimeNoContent


-- *** updateEmailCampaign0

-- | @PUT \/emailCampaigns\/{campaignId}@
-- 
-- Update an email campaign
-- 
-- AuthMethod: 'AuthApiKeyApiKey'
-- 
updateEmailCampaign0
  :: (Consumes UpdateEmailCampaign0 MimeJSON, MimeRender MimeJSON UpdateEmailCampaign)
  => UpdateEmailCampaign -- ^ "emailCampaign" -  Values to update a campaign
  -> CampaignId -- ^ "campaignId" -  Id of the campaign
  -> SendinBlueRequest UpdateEmailCampaign0 MimeJSON NoContent MimeNoContent
updateEmailCampaign0 emailCampaign (CampaignId campaignId) =
  _mkRequest "PUT" ["/emailCampaigns/",toPath campaignId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyApiKey)
    `setBodyParam` emailCampaign

data UpdateEmailCampaign0 

-- | /Body Param/ "emailCampaign" - Values to update a campaign
instance HasBodyParam UpdateEmailCampaign0 UpdateEmailCampaign 

-- | @application/json@
instance Consumes UpdateEmailCampaign0 MimeJSON

instance Produces UpdateEmailCampaign0 MimeNoContent


-- *** uploadImageToGallery0

-- | @POST \/emailCampaigns\/images@
-- 
-- Upload an image to your account's image gallery
-- 
-- AuthMethod: 'AuthApiKeyApiKey'
-- 
uploadImageToGallery0
  :: (Consumes UploadImageToGallery0 MimeJSON, MimeRender MimeJSON UploadImageToGallery)
  => UploadImageToGallery -- ^ "uploadImage" -  Parameters to upload an image
  -> SendinBlueRequest UploadImageToGallery0 MimeJSON NoContent MimeNoContent
uploadImageToGallery0 uploadImage =
  _mkRequest "POST" ["/emailCampaigns/images"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyApiKey)
    `setBodyParam` uploadImage

data UploadImageToGallery0 

-- | /Body Param/ "uploadImage" - Parameters to upload an image
instance HasBodyParam UploadImageToGallery0 UploadImageToGallery 

-- | @application/json@
instance Consumes UploadImageToGallery0 MimeJSON

instance Produces UploadImageToGallery0 MimeNoContent

