{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE PartialTypeSignatures #-}

module Main where

import Data.Typeable (Proxy(..))
import Test.Hspec
import Test.Hspec.QuickCheck

import PropMime
import Instances ()

import SendinBlue.Model
import SendinBlue.MimeTypes

main :: IO ()
main =
  hspec $ modifyMaxSize (const 5) $ do
    describe "JSON instances" $ do
      pure ()
      propMimeEq MimeJSON (Proxy :: Proxy AddChildDomain)
      propMimeEq MimeJSON (Proxy :: Proxy AddContactToList)
      propMimeEq MimeJSON (Proxy :: Proxy AddCredits)
      propMimeEq MimeJSON (Proxy :: Proxy CreateAttribute)
      propMimeEq MimeJSON (Proxy :: Proxy CreateAttributeEnumeration)
      propMimeEq MimeJSON (Proxy :: Proxy CreateChild)
      propMimeEq MimeJSON (Proxy :: Proxy CreateContact)
      propMimeEq MimeJSON (Proxy :: Proxy CreateEmailCampaign)
      propMimeEq MimeJSON (Proxy :: Proxy CreateEmailCampaignRecipients)
      propMimeEq MimeJSON (Proxy :: Proxy CreateEmailCampaignSender)
      propMimeEq MimeJSON (Proxy :: Proxy CreateList)
      propMimeEq MimeJSON (Proxy :: Proxy CreateModel)
      propMimeEq MimeJSON (Proxy :: Proxy CreateReseller)
      propMimeEq MimeJSON (Proxy :: Proxy CreateSender)
      propMimeEq MimeJSON (Proxy :: Proxy CreateSenderIps)
      propMimeEq MimeJSON (Proxy :: Proxy CreateSenderModel)
      propMimeEq MimeJSON (Proxy :: Proxy CreateSmsCampaign)
      propMimeEq MimeJSON (Proxy :: Proxy CreateSmsCampaignRecipients)
      propMimeEq MimeJSON (Proxy :: Proxy CreateSmtpEmail)
      propMimeEq MimeJSON (Proxy :: Proxy CreateSmtpTemplate)
      propMimeEq MimeJSON (Proxy :: Proxy CreateSmtpTemplateSender)
      propMimeEq MimeJSON (Proxy :: Proxy CreateUpdateContactModel)
      propMimeEq MimeJSON (Proxy :: Proxy CreateUpdateFolder)
      propMimeEq MimeJSON (Proxy :: Proxy CreateWebhook)
      propMimeEq MimeJSON (Proxy :: Proxy CreatedProcessId)
      propMimeEq MimeJSON (Proxy :: Proxy DeleteHardbounces)
      propMimeEq MimeJSON (Proxy :: Proxy EmailExportRecipients)
      propMimeEq MimeJSON (Proxy :: Proxy ErrorModel)
      propMimeEq MimeJSON (Proxy :: Proxy GetAccountMarketingAutomation)
      propMimeEq MimeJSON (Proxy :: Proxy GetAccountPlan)
      propMimeEq MimeJSON (Proxy :: Proxy GetAccountRelay)
      propMimeEq MimeJSON (Proxy :: Proxy GetAccountRelayData)
      propMimeEq MimeJSON (Proxy :: Proxy GetAggregatedReport)
      propMimeEq MimeJSON (Proxy :: Proxy GetAttributes)
      propMimeEq MimeJSON (Proxy :: Proxy GetAttributesAttributes)
      propMimeEq MimeJSON (Proxy :: Proxy GetAttributesEnumeration)
      propMimeEq MimeJSON (Proxy :: Proxy GetCampaignOverview)
      propMimeEq MimeJSON (Proxy :: Proxy GetCampaignRecipients)
      propMimeEq MimeJSON (Proxy :: Proxy GetCampaignStats)
      propMimeEq MimeJSON (Proxy :: Proxy GetChildAccountCreationStatus)
      propMimeEq MimeJSON (Proxy :: Proxy GetChildDomain)
      propMimeEq MimeJSON (Proxy :: Proxy GetChildDomains)
      propMimeEq MimeJSON (Proxy :: Proxy GetChildInfoApiKeys)
      propMimeEq MimeJSON (Proxy :: Proxy GetChildInfoApiKeysV2)
      propMimeEq MimeJSON (Proxy :: Proxy GetChildInfoApiKeysV3)
      propMimeEq MimeJSON (Proxy :: Proxy GetChildInfoCredits)
      propMimeEq MimeJSON (Proxy :: Proxy GetChildInfoStatistics)
      propMimeEq MimeJSON (Proxy :: Proxy GetChildrenList)
      propMimeEq MimeJSON (Proxy :: Proxy GetClient)
      propMimeEq MimeJSON (Proxy :: Proxy GetContactCampaignStats)
      propMimeEq MimeJSON (Proxy :: Proxy GetContactCampaignStatsClicked)
      propMimeEq MimeJSON (Proxy :: Proxy GetContactCampaignStatsOpened)
      propMimeEq MimeJSON (Proxy :: Proxy GetContactCampaignStatsTransacAttributes)
      propMimeEq MimeJSON (Proxy :: Proxy GetContactCampaignStatsUnsubscriptions)
      propMimeEq MimeJSON (Proxy :: Proxy GetContactDetails)
      propMimeEq MimeJSON (Proxy :: Proxy GetContacts)
      propMimeEq MimeJSON (Proxy :: Proxy GetDeviceBrowserStats)
      propMimeEq MimeJSON (Proxy :: Proxy GetEmailCampaigns)
      propMimeEq MimeJSON (Proxy :: Proxy GetEmailEventReport)
      propMimeEq MimeJSON (Proxy :: Proxy GetEmailEventReportEvents)
      propMimeEq MimeJSON (Proxy :: Proxy GetExtendedCampaignOverviewSender)
      propMimeEq MimeJSON (Proxy :: Proxy GetExtendedCampaignStats)
      propMimeEq MimeJSON (Proxy :: Proxy GetExtendedClientAddress)
      propMimeEq MimeJSON (Proxy :: Proxy GetExtendedContactDetailsStatistics)
      propMimeEq MimeJSON (Proxy :: Proxy GetExtendedContactDetailsStatisticsClicked)
      propMimeEq MimeJSON (Proxy :: Proxy GetExtendedContactDetailsStatisticsLinks)
      propMimeEq MimeJSON (Proxy :: Proxy GetExtendedContactDetailsStatisticsMessagesSent)
      propMimeEq MimeJSON (Proxy :: Proxy GetExtendedContactDetailsStatisticsOpened)
      propMimeEq MimeJSON (Proxy :: Proxy GetExtendedContactDetailsStatisticsUnsubscriptions)
      propMimeEq MimeJSON (Proxy :: Proxy GetExtendedContactDetailsStatisticsUnsubscriptionsAdminUnsubscription)
      propMimeEq MimeJSON (Proxy :: Proxy GetExtendedContactDetailsStatisticsUnsubscriptionsUserUnsubscription)
      propMimeEq MimeJSON (Proxy :: Proxy GetExtendedListCampaignStats)
      propMimeEq MimeJSON (Proxy :: Proxy GetFolder)
      propMimeEq MimeJSON (Proxy :: Proxy GetFolderLists)
      propMimeEq MimeJSON (Proxy :: Proxy GetFolders)
      propMimeEq MimeJSON (Proxy :: Proxy GetIp)
      propMimeEq MimeJSON (Proxy :: Proxy GetIpFromSender)
      propMimeEq MimeJSON (Proxy :: Proxy GetIps)
      propMimeEq MimeJSON (Proxy :: Proxy GetIpsFromSender)
      propMimeEq MimeJSON (Proxy :: Proxy GetList)
      propMimeEq MimeJSON (Proxy :: Proxy GetLists)
      propMimeEq MimeJSON (Proxy :: Proxy GetProcess)
      propMimeEq MimeJSON (Proxy :: Proxy GetProcesses)
      propMimeEq MimeJSON (Proxy :: Proxy GetReports)
      propMimeEq MimeJSON (Proxy :: Proxy GetReportsReports)
      propMimeEq MimeJSON (Proxy :: Proxy GetSendersList)
      propMimeEq MimeJSON (Proxy :: Proxy GetSendersListIps)
      propMimeEq MimeJSON (Proxy :: Proxy GetSendersListSenders)
      propMimeEq MimeJSON (Proxy :: Proxy GetSharedTemplateUrl)
      propMimeEq MimeJSON (Proxy :: Proxy GetSmsCampaignOverview)
      propMimeEq MimeJSON (Proxy :: Proxy GetSmsCampaignStats)
      propMimeEq MimeJSON (Proxy :: Proxy GetSmsCampaigns)
      propMimeEq MimeJSON (Proxy :: Proxy GetSmsEventReport)
      propMimeEq MimeJSON (Proxy :: Proxy GetSmsEventReportEvents)
      propMimeEq MimeJSON (Proxy :: Proxy GetSmtpTemplateOverview)
      propMimeEq MimeJSON (Proxy :: Proxy GetSmtpTemplateOverviewSender)
      propMimeEq MimeJSON (Proxy :: Proxy GetSmtpTemplates)
      propMimeEq MimeJSON (Proxy :: Proxy GetSsoToken)
      propMimeEq MimeJSON (Proxy :: Proxy GetStatsByBrowser)
      propMimeEq MimeJSON (Proxy :: Proxy GetStatsByDevice)
      propMimeEq MimeJSON (Proxy :: Proxy GetStatsByDomain)
      propMimeEq MimeJSON (Proxy :: Proxy GetTransacAggregatedSmsReport)
      propMimeEq MimeJSON (Proxy :: Proxy GetTransacBlockedContacts)
      propMimeEq MimeJSON (Proxy :: Proxy GetTransacBlockedContactsContacts)
      propMimeEq MimeJSON (Proxy :: Proxy GetTransacBlockedContactsReason)
      propMimeEq MimeJSON (Proxy :: Proxy GetTransacEmailContent)
      propMimeEq MimeJSON (Proxy :: Proxy GetTransacEmailContentEvents)
      propMimeEq MimeJSON (Proxy :: Proxy GetTransacEmailsList)
      propMimeEq MimeJSON (Proxy :: Proxy GetTransacEmailsListTransactionalEmails)
      propMimeEq MimeJSON (Proxy :: Proxy GetTransacSmsReport)
      propMimeEq MimeJSON (Proxy :: Proxy GetTransacSmsReportReports)
      propMimeEq MimeJSON (Proxy :: Proxy GetWebhook)
      propMimeEq MimeJSON (Proxy :: Proxy GetWebhooks)
      propMimeEq MimeJSON (Proxy :: Proxy ManageIp)
      propMimeEq MimeJSON (Proxy :: Proxy PostContactInfo)
      propMimeEq MimeJSON (Proxy :: Proxy PostContactInfoContacts)
      propMimeEq MimeJSON (Proxy :: Proxy PostSendFailed)
      propMimeEq MimeJSON (Proxy :: Proxy PostSendSmsTestFailed)
      propMimeEq MimeJSON (Proxy :: Proxy RemainingCreditModel)
      propMimeEq MimeJSON (Proxy :: Proxy RemainingCreditModelChild)
      propMimeEq MimeJSON (Proxy :: Proxy RemainingCreditModelReseller)
      propMimeEq MimeJSON (Proxy :: Proxy RemoveContactFromList)
      propMimeEq MimeJSON (Proxy :: Proxy RemoveCredits)
      propMimeEq MimeJSON (Proxy :: Proxy RequestContactExport)
      propMimeEq MimeJSON (Proxy :: Proxy RequestContactImport)
      propMimeEq MimeJSON (Proxy :: Proxy RequestContactImportNewList)
      propMimeEq MimeJSON (Proxy :: Proxy RequestSmsRecipientExport)
      propMimeEq MimeJSON (Proxy :: Proxy SendEmail)
      propMimeEq MimeJSON (Proxy :: Proxy SendEmailAttachment)
      propMimeEq MimeJSON (Proxy :: Proxy SendReport)
      propMimeEq MimeJSON (Proxy :: Proxy SendReportEmail)
      propMimeEq MimeJSON (Proxy :: Proxy SendSms)
      propMimeEq MimeJSON (Proxy :: Proxy SendSmtpEmail)
      propMimeEq MimeJSON (Proxy :: Proxy SendSmtpEmailAttachment)
      propMimeEq MimeJSON (Proxy :: Proxy SendSmtpEmailBcc)
      propMimeEq MimeJSON (Proxy :: Proxy SendSmtpEmailCc)
      propMimeEq MimeJSON (Proxy :: Proxy SendSmtpEmailReplyTo)
      propMimeEq MimeJSON (Proxy :: Proxy SendSmtpEmailSender)
      propMimeEq MimeJSON (Proxy :: Proxy SendSmtpEmailTo)
      propMimeEq MimeJSON (Proxy :: Proxy SendTemplateEmail)
      propMimeEq MimeJSON (Proxy :: Proxy SendTestEmail)
      propMimeEq MimeJSON (Proxy :: Proxy SendTestSms)
      propMimeEq MimeJSON (Proxy :: Proxy SendTransacSms)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateAttribute)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateAttributeEnumeration)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateCampaignStatus)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateChild)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateChildAccountStatus)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateChildDomain)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateContact)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateEmailCampaign)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateEmailCampaignRecipients)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateEmailCampaignSender)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateList)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateSender)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateSmsCampaign)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateSmtpTemplate)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateSmtpTemplateSender)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateWebhook)
      propMimeEq MimeJSON (Proxy :: Proxy GetChildInfo)
      propMimeEq MimeJSON (Proxy :: Proxy GetExtendedCampaignOverview)
      propMimeEq MimeJSON (Proxy :: Proxy GetExtendedClient)
      propMimeEq MimeJSON (Proxy :: Proxy GetExtendedContactDetails)
      propMimeEq MimeJSON (Proxy :: Proxy GetExtendedList)
      propMimeEq MimeJSON (Proxy :: Proxy GetSmsCampaign)
      propMimeEq MimeJSON (Proxy :: Proxy GetAccount)
      propMimeEq MimeJSON (Proxy :: Proxy GetEmailCampaign)
      
